CREATE_UPDATE = "CREATE_UPDATE"
UPDATE = "UPDATE"
CREATE = "CREATE"
DELETE = "DELETE"
DETAILS = "DETAILS"
PAGINATED_LIST = "PAGINATED_LIST"
LIST = "LIST"
SIMPLE_GET = "SIMPLE_GET"

BULK_DELETE = "BULK_DELETE"
BULK_CREATE_UPDATE = "BULK_CREATE_UPDATE"
BULK_UPDATE = "BULK_UPDATE"
BULK_CREATE = "BULK_CREATE"

MESSAGE_RESPONSE: str = "MessageResponse"
ERROR_DETAILS_RESPONSE: str = "ErrorDetailsResponse"

